import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "./Navbar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className="m-auto max-w-7xl p-10">{children}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
