import "./globals.css";
import Navbar from "./Navbar";
import { Providers } from "./providers";
import ClientWrapper from "./ClientWrapper";
import ThemeProvider from "@/components/theme-provider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <ClientWrapper>
              <div className="m-auto max-w-[1920px] p-10">{children}</div>
            </ClientWrapper>
            <div className="bg-background fixed top-0 -z-20 min-h-screen w-full">
              {/* Violet Storm Background with Top Glow */}
              <div
                className="absolute inset-0 -z-10"
                style={{
                  backgroundImage:
                    "radial-gradient(ellipse 80% 60% at 50% 0%, rgba(139, 92, 246, 0.25), transparent 70%)",
                }}
              />
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
